spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/smarthouse
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  liquibase:
    enabled: false


app:
  house-rules:
    rate: "0 * * * * *"
  weather-service:
    cred:
      token: ""
    current-weather-endpoint: "/data/2.5/weather"
    baseUrl: "https://api.openweathermap.org"
    # Saratov
    coordinate:
      lon: 46.0
      lat: 51.32
    scheduler:
      rate: 600000